import Link from "next/link";
import type { ReactNode } from "react";
import styles from "./legal-page.module.css";
/* eslint-disable @next/next/no-img-element -- supplied Pixel SVG identity asset. */

type LegalSection = { id: string; title: string; children: ReactNode };

const publishingNotice = (
  <aside className={styles.notice} aria-label="Pendências antes da publicação">
    <strong>Antes de publicar</strong>
    <p>Complete a identificação jurídica da responsável e o canal oficial de privacidade nos campos abaixo. Este texto também precisa de revisão jurídica para a operação efetivamente adotada pela Prime Creative.</p>
    <dl>
      <div><dt>Responsável legal</dt><dd>[preencher razão social e CNPJ, se aplicável]</dd></div>
      <div><dt>Canal de privacidade</dt><dd>[preencher e-mail ou canal oficial de atendimento]</dd></div>
    </dl>
  </aside>
);

const privacySections: LegalSection[] = [
  { id: "responsavel", title: "1. Responsável por esta política", children: <><p>O Pixel é um produto da Prime Creative. A Prime Creative é responsável por esta Política de Privacidade e pelo tratamento de dados descrito neste documento no contexto do Pixel.</p><p>A identificação jurídica completa e o canal oficial de contato devem ser preenchidos antes da publicação definitiva desta página.</p></> },
  { id: "dados", title: "2. Dados tratados no Pixel", children: <><p>O Pixel utiliza a autenticação compartilhada do ecossistema Órbita, baseada em Supabase. Para permitir o acesso autorizado, o serviço pode tratar os dados de conta e de vínculo profissional necessários para identificar a pessoa membro e o respectivo espaço de trabalho, como nome, e-mail, identificadores técnicos de sessão e informações de associação à equipe.</p><p>As criações, textos, escolhas de template e imagens enviadas para a composição são mantidos no armazenamento local do navegador, por meio do IndexedDB. Esses dados não formam, por si, uma biblioteca hospedada em servidor pelo Pixel.</p></> },
  { id: "finalidades", title: "3. Finalidades do uso", children: <><p>Os dados são usados para autenticar o acesso ao Pixel, vincular o uso ao espaço de trabalho autorizado, permitir a criação e a edição de cards e carrosséis, processar imagens no fluxo escolhido pela pessoa usuária e disponibilizar exportações em PNG, JPG ou ZIP.</p><p>O Pixel não declara nesta política usos que não estejam associados à operação do produto. Caso novas finalidades sejam implementadas, esta página deverá ser atualizada antes de entrarem em operação.</p></> },
  { id: "armazenamento-local", title: "4. Armazenamento local e exportações", children: <><p>As criações do Pixel permanecem no navegador em que foram feitas, usando o IndexedDB. Isso significa que limpar dados do navegador, trocar de dispositivo ou usar outro perfil pode afetar a disponibilidade local dessas criações.</p><p>As exportações locais em PNG, JPG e ZIP são baixadas para o dispositivo da pessoa usuária. A gestão, a guarda e o eventual compartilhamento desses arquivos fora do Pixel dependem das escolhas da própria pessoa usuária e das regras aplicáveis ao seu ambiente de trabalho.</p></> },
  { id: "drive", title: "5. Google Drive opcional", children: <><p>A conexão com o Google Drive é opcional e só é iniciada quando a pessoa escolhe conectar sua conta. O Pixel solicita o escopo <code>https://www.googleapis.com/auth/drive.file</code>, restrito aos arquivos criados ou abertos pelo aplicativo, e cria uma pasta chamada <strong>Pixel</strong> no Meu Drive da conta conectada.</p><p>Quando a integração estiver configurada e a pessoa optar por utilizá-la, o Pixel poderá enviar à pasta Pixel as exportações PNG ou JPG e, em carrosséis, as imagens individuais e o arquivo ZIP. O recurso não realiza sincronização bidirecional, importação de biblioteca, listagem geral de arquivos nem solicita o escopo amplo <code>drive</code>.</p><p>O refresh token necessário para a conexão é mantido somente no servidor, cifrado com AES-256-GCM. Access tokens são obtidos sob demanda e não são enviados ao navegador. O estado temporário do OAuth é assinado, mantido em cookie HttpOnly com SameSite=Lax por até dez minutos e não contém tokens.</p><p>A desconexão tenta revogar o token no Google e remove a conexão cifrada armazenada pelo Pixel. Se a revogação externa não for concluída, a pessoa também pode remover o acesso nas configurações de apps de terceiros da sua Conta Google.</p></> },
  { id: "compartilhamento", title: "6. Compartilhamento e operadores", children: <><p>O Pixel utiliza a infraestrutura de autenticação e dados compartilhada do ecossistema Órbita/Supabase para a sessão e o vínculo autorizado à equipe. A integração opcional com o Google Drive envolve o Google apenas quando a pessoa escolhe conectar sua conta e enviar exportações.</p><p>Não há venda de dados pessoais nem compartilhamento descrito aqui para finalidades publicitárias próprias do Pixel. Serviços de infraestrutura podem tratar dados técnicos necessários para operar suas respectivas funcionalidades, sujeitos às suas configurações e políticas aplicáveis.</p></> },
  { id: "retencao", title: "7. Retenção e limitações", children: <><p>Como as criações são armazenadas localmente no navegador, sua permanência depende das configurações do navegador, do dispositivo e das ações da pessoa usuária. O Pixel não promete recuperação de criações que tenham sido removidas do armazenamento local.</p><p>Dados de autenticação e de vínculo seguem a operação do ambiente compartilhado do Órbita. Uma conexão opcional com o Google Drive permanece enquanto estiver ativa ou até ser desconectada, observadas as limitações técnicas do fluxo de revogação descritas acima.</p></> },
  { id: "seguranca", title: "8. Segurança", children: <><p>O Pixel adota medidas técnicas compatíveis com sua implementação atual, como sessão autenticada, separação entre browser e operações sensíveis do servidor e cifra do refresh token do Google Drive quando a integração é usada.</p><p>Nenhum sistema pode garantir segurança absoluta. Por isso, a pessoa usuária deve proteger suas credenciais, manter o navegador e o dispositivo atualizados e comunicar situações suspeitas pelo canal oficial que será informado nesta página.</p></> },
  { id: "direitos", title: "9. Direitos de titulares", children: <><p>Nos termos da legislação aplicável, incluindo a LGPD quando aplicável, a pessoa titular pode solicitar informações sobre o tratamento de seus dados e exercer os direitos previstos em lei, tais como confirmação de tratamento, acesso, correção, anonimização, bloqueio, eliminação, portabilidade, informação sobre compartilhamentos e revisão de consentimento, quando cabíveis.</p><p>Para solicitar esses direitos, use o canal oficial de privacidade a ser preenchido antes da publicação. Algumas solicitações podem depender da relação da pessoa com o espaço de trabalho e das obrigações legais ou técnicas aplicáveis.</p></> },
  { id: "atualizacoes", title: "10. Atualizações desta política", children: <p>Esta política pode ser atualizada para refletir alterações no Pixel, em seus fluxos de dados ou em requisitos legais. A versão vigente será disponibilizada nesta página, com a data de atualização indicada abaixo.</p> },
];

const termsSections: LegalSection[] = [
  { id: "aceite", title: "1. Aceitação e escopo", children: <><p>Estes Termos de Uso regulam o acesso ao Pixel, produto da Prime Creative voltado à criação de cards e carrosséis. Ao acessar ou utilizar o Pixel, a pessoa usuária concorda com estes termos e com a <Link href="/privacidade">Política de Privacidade</Link>.</p><p>Antes da publicação definitiva, a Prime Creative deve completar sua identificação jurídica e seu canal oficial de contato, além de submeter este texto à revisão jurídica.</p></> },
  { id: "acesso", title: "2. Acesso e conta", children: <><p>O acesso ao Pixel depende de sessão válida na autenticação compartilhada do ecossistema Órbita/Supabase e de vínculo ativo com o espaço de trabalho autorizado. O Pixel não cria uma conta independente para essa finalidade.</p><p>A pessoa usuária é responsável por manter suas credenciais em sigilo e por usar o produto apenas dentro das permissões que lhe foram concedidas. O acesso pode ficar indisponível quando a sessão, o vínculo ou a configuração do ambiente não estiverem válidos.</p></> },
  { id: "uso", title: "3. Uso permitido", children: <><p>O Pixel permite compor peças visuais a partir de templates, textos, imagens e dados inseridos pela pessoa usuária, bem como exportar os resultados em PNG, JPG e, quando aplicável, ZIP.</p><p>Você deve usar o Pixel de forma lícita, respeitando direitos autorais, direitos de imagem, marcas, dados pessoais e demais direitos de terceiros. Não envie conteúdo ilícito, malicioso, enganoso ou para o qual você não tenha autorização de uso.</p></> },
  { id: "conteudo", title: "4. Conteúdo enviado e exportado", children: <><p>A pessoa usuária é responsável pelos textos, imagens, marcas e demais materiais que insere no Pixel e pelas decisões de publicação, distribuição ou uso das exportações. O Pixel não substitui a revisão editorial, jurídica, publicitária ou de acessibilidade que possa ser necessária para cada conteúdo.</p><p>As criações são mantidas localmente no navegador pelo IndexedDB. Exportações locais são baixadas ao dispositivo da pessoa usuária. A exclusão de dados do navegador, a mudança de dispositivo ou de perfil podem tornar essas criações indisponíveis.</p></> },
  { id: "drive", title: "5. Google Drive opcional", children: <><p>O Google Drive é uma extensão opcional. Ao escolher conectar uma conta Google, a pessoa usuária autoriza o fluxo OAuth com o escopo <code>drive.file</code> e a criação de uma pasta chamada <strong>Pixel</strong> em seu Meu Drive.</p><p>Quando solicitado pela pessoa usuária, o Pixel envia para essa pasta as exportações PNG ou JPG e, nos carrosséis, as imagens individuais e o ZIP. O recurso não sincroniza bibliotecas, não importa arquivos do Drive, não lista os arquivos gerais da conta e não usa o escopo amplo <code>drive</code>.</p><p>A conexão pode ser desfeita no Pixel. O sistema tenta revogar a autorização no Google e remove a conexão cifrada armazenada pelo Pixel; se a revogação no Google falhar, a pessoa usuária poderá removê-la também nas configurações da sua Conta Google.</p></> },
  { id: "disponibilidade", title: "6. Disponibilidade e alterações", children: <><p>O Pixel pode receber atualizações, correções, mudanças de interface e ajustes de funcionalidades. A Prime Creative não promete disponibilidade ininterrupta, preservação indefinida de criações locais, resultado específico de design ou compatibilidade com todos os navegadores e dispositivos.</p><p>Funcionalidades externas, como autenticação compartilhada e Google Drive, dependem também de suas respectivas configurações e serviços. A indisponibilidade desses serviços pode limitar recursos do Pixel.</p></> },
  { id: "suspensao", title: "7. Suspensão ou encerramento de acesso", children: <p>O acesso pode ser suspenso ou encerrado quando houver perda do vínculo autorizado, necessidade de segurança, uso que viole estes termos ou obrigação legal. Quando possível, isso será tratado conforme as regras do ambiente de trabalho e da relação aplicável com a Prime Creative.</p> },
  { id: "responsabilidade", title: "8. Limites de responsabilidade", children: <p>Na extensão permitida pela legislação aplicável, o Pixel é disponibilizado como ferramenta de criação. A Prime Creative não garante que todo conteúdo gerado ou exportado esteja adequado a uma finalidade específica, a requisitos de terceiros ou a regras de plataformas externas. Nada nestes termos limita direitos que não possam ser limitados por lei.</p> },
  { id: "contato", title: "9. Contato e atualizações", children: <><p>Questões sobre estes termos, uso do Pixel ou privacidade devem ser direcionadas ao canal oficial da Prime Creative, a ser informado antes da publicação definitiva.</p><p>Estes termos podem ser atualizados para refletir alterações no produto, nos serviços associados ou na legislação. A versão vigente ficará disponível nesta página.</p></> },
];

function LegalHeader() {
  return <header className={styles.header}><Link href="/" className={styles.brand} aria-label="Voltar ao Pixel"><img src="/brand/pixel/signature/lockup-wide-ink.svg" alt="Pixel, um produto Prime Creative" /></Link><Link href="/" className={styles.loginLink}>Entrar no Pixel</Link></header>;
}

function LegalFooter({ current }: { current: "privacy" | "terms" }) {
  return <footer className={styles.footer}><span>Pixel · Prime Creative</span><nav aria-label="Documentos legais">{current !== "privacy" && <Link href="/privacidade">Política de Privacidade</Link>}{current !== "terms" && <Link href="/termos">Termos de Uso</Link>}<Link href="/">Entrar</Link></nav></footer>;
}

export function LegalPage({ kind }: { kind: "privacy" | "terms" }) {
  const isPrivacy = kind === "privacy";
  const sections = isPrivacy ? privacySections : termsSections;
  const title = isPrivacy ? "Política de Privacidade" : "Termos de Uso";
  const subtitle = isPrivacy ? "Como o Pixel trata dados de acesso, criações locais e a conexão opcional com o Google Drive." : "As condições para usar o Pixel e suas exportações com clareza e responsabilidade.";
  return <main className={styles.shell}><LegalHeader /><article className={styles.document}><div className={styles.hero}><p className="eyebrow">Pixel · Prime Creative</p><h1>{title}</h1><p>{subtitle}</p><small>Última atualização: 10 de outubro de 2026</small></div>{publishingNotice}<div className={styles.content}>{sections.map((section) => <section id={section.id} key={section.id}><h2>{section.title}</h2>{section.children}</section>)}</div></article><LegalFooter current={kind} /></main>;
}
