import Link from "next/link";
import type { ReactNode } from "react";
import styles from "./legal-page.module.css";
/* eslint-disable @next/next/no-img-element -- supplied Pixel SVG identity asset. */

type LegalSection = { id: string; title: string; children: ReactNode };

const publishingNotice = (
  <aside className={styles.notice} aria-label="Pendências antes da publicação">
    <strong>Rascunho: não publicar ainda</strong>
    <p>Esta versão foi revisada contra o código do Pixel, mas ainda depende de confirmação operacional e de revisão final por advogado brasileiro. Ela não identifica uma pessoa jurídica: Prime Creative é o nome comercial do produto.</p>
    <dl>
      <div><dt>Controlador</dt><dd>José Rodrigues da Costa Netto, pessoa física responsável pela operação do Pixel sob o nome comercial Prime Creative.</dd></div>
      <div><dt>Canal de privacidade</dt><dd><a href="mailto:contato@primecreative.com.br">contato@primecreative.com.br</a></dd></div>
      <div><dt>Operação e fornecedores</dt><dd>Confirmar bases legais, prazos de retenção e regiões/garantias de transferências internacionais antes do lançamento.</dd></div>
    </dl>
  </aside>
);

const privacySections: LegalSection[] = [
  { id: "controlador", title: "1. Quem decide sobre o tratamento", children: <><p>Pixel é um produto apresentado sob o nome comercial Prime Creative. O controlador dos dados pessoais tratados no contexto do Pixel é José Rodrigues da Costa Netto, pessoa física responsável pela operação do produto. A Prime Creative não é apresentada neste documento como pessoa jurídica e não possui CNPJ.</p><p>Esta página não informa CPF ou endereço residencial do controlador. O canal de privacidade é <a href="mailto:contato@primecreative.com.br">contato@primecreative.com.br</a>.</p></> },
  { id: "dados-e-finalidades", title: "2. Dados tratados e finalidades", children: <><p>Nesta fase, o Pixel é um produto de uso interno para pessoas com acesso ativo às plataformas da Prime Creative; não é oferecido ao público externo. Para controlar o acesso, o Pixel usa a autenticação compartilhada do ambiente Órbita/Supabase. O código trata dados de conta e de vínculo profissional necessários para verificar a sessão e a associação ativa à equipe e ao espaço de trabalho, incluindo nome, e-mail, identificadores técnicos de usuário e de sessão, situação do vínculo e registro de último acesso.</p><p>Para criar peças, o Pixel trata no navegador textos, escolhas de template, informações de marca e imagens adicionadas pela pessoa usuária. Esse conteúdo é usado para compor cards e carrosséis e permitir a exportação em PNG, JPG ou ZIP. A pessoa usuária não deve inserir no Pixel conteúdo pessoal, sensível ou de terceiros sem base legítima e autorização quando necessária.</p><p>O tratamento deve se limitar às finalidades de acesso autorizado, operação da ferramenta, segurança, atendimento de solicitações e integrações que a pessoa escolher usar. A base legal aplicável a cada fluxo — por exemplo, execução de relação contratual ou procedimentos correlatos, cumprimento de obrigação legal, exercício regular de direitos, segurança e legítimo interesse, quando cabível — deverá ser confirmada pelo controlador no mapeamento de tratamento antes da publicação.</p></> },
  { id: "armazenamento-local", title: "3. Armazenamento local, preferências e exportações", children: <><p>As criações e imagens usadas nelas são guardadas no navegador em que foram feitas, por meio do IndexedDB. Preferências de retenção, marcas cadastradas e preferências de interface também podem permanecer no armazenamento local do navegador. O Pixel não mantém, pelo código atualmente revisado, uma biblioteca centralizada dessas criações.</p><p>A pessoa pode escolher retenção local de 15, 30 ou 90 dias, ou um período personalizado de 1 a 365 dias. A expiração é aplicada quando o aplicativo volta a carregar e regrava o armazenamento local; por isso, não é uma garantia de eliminação automática em data e hora exatas se o navegador não for aberto. Limpar os dados do navegador, trocar de perfil ou dispositivo, usar modo privado ou excluir a criação pode torná-la indisponível.</p><p>Exportações locais são baixadas ao dispositivo da pessoa usuária. Depois do download, a guarda, o compartilhamento e a exclusão desses arquivos passam a depender das escolhas da pessoa usuária e das regras aplicáveis ao seu dispositivo e ambiente de trabalho.</p></> },
  { id: "ia-opcional", title: "4. Interpretação de briefing por IA, quando habilitada", children: <><p>Se a funcionalidade de interpretação de briefing estiver habilitada no ambiente e a pessoa escolher usá-la, o Pixel envia ao serviço de IA o texto do briefing, o contexto de público ou tom de voz e o template selecionado, para devolver uma sugestão estruturada de texto. A implementação atual usa o Vercel AI Gateway com o modelo configurado <code>anthropic/claude-sonnet-4.6</code>.</p><p>O código revisado não envia imagens nem arquivos de exportação a esse fluxo de IA e não grava, por si só, o briefing ou a resposta em um banco próprio do Pixel. A sugestão pode, contudo, ser salva localmente se a pessoa a usar para criar uma peça. Os prazos e demais práticas dos fornecedores de IA devem ser confirmados antes da produção; não use esse recurso para dados pessoais sensíveis, confidenciais ou de terceiros sem avaliação e autorização apropriadas.</p></> },
  { id: "drive", title: "5. Google Drive opcional", children: <><p>A conexão com o Google Drive é opcional e começa apenas quando a pessoa escolhe conectar sua conta. O Pixel solicita o escopo <code>https://www.googleapis.com/auth/drive.file</code> e, na implementação atual, cria uma pasta chamada <strong>Pixel</strong> no Meu Drive da conta conectada. O código não implementa importação, sincronização bidirecional, navegação ou listagem geral da biblioteca da conta e não solicita o escopo amplo <code>drive</code>.</p><p>Somente após a conexão e por comando da pessoa usuária, o Pixel envia à pasta as exportações geradas: PNG ou JPG e, em carrosséis, as imagens individuais e o ZIP. Esses arquivos podem conter o conteúdo e as imagens incorporados à peça. Não há envio automático de criações ao Drive.</p><p>Para manter a conexão, o refresh token é guardado no servidor em tabela do Supabase prevista para a integração, cifrado com AES-256-GCM; access tokens são obtidos sob demanda e não são enviados ao navegador. O estado do OAuth fica em cookie temporário assinado, <code>HttpOnly</code> e <code>SameSite=Lax</code>, por no máximo dez minutos, sem tokens. A conexão permanece até a desconexão ou outra invalidação técnica aplicável.</p><p>Ao desconectar, o Pixel tenta revogar o token no Google e apaga a conexão cifrada que mantém. Se a revogação no Google não for concluída, a exclusão local ainda é tentada e a pessoa poderá remover o acesso nas configurações de apps de terceiros da Conta Google.</p><p>O uso das informações recebidas dos escopos do Google Workspace observará a <a href="https://developers.google.com/terms/api-services-user-data-policy" target="_blank" rel="noreferrer">Política de Dados do Usuário dos Serviços de API do Google</a>, inclusive os requisitos de Uso Limitado.</p></> },
  { id: "cookies", title: "6. Cookies e tecnologias semelhantes", children: <><p>O Pixel usa cookies e armazenamento local estritamente necessários para manter a sessão compartilhada do Supabase, proteger o fluxo de OAuth do Google Drive e lembrar preferências de interface e do próprio navegador. O cookie temporário do OAuth do Drive é descrito na seção anterior. A sessão é necessária para áreas autenticadas; sem ela, o acesso não funciona.</p><p>Na implementação revisada não há ferramenta de publicidade comportamental, analytics ou pixel de rastreamento adicionada pelo Pixel. Caso cookies não essenciais, medição ou novas tecnologias sejam introduzidos, esta política e a interface de consentimento aplicável deverão ser atualizadas antes de seu uso.</p></> },
  { id: "compartilhamento", title: "7. Compartilhamento, operadores e transferências internacionais", children: <><p>Para os fluxos descritos, o Pixel depende do ambiente compartilhado do Órbita/Supabase para autenticação, vínculo de equipe e, se o Drive for usado, para a conexão cifrada. Quando escolhida, a integração envolve o Google para autorização e envio das exportações selecionadas. Quando escolhida e habilitada, a interpretação de briefing envolve o Vercel AI Gateway e o provedor do modelo configurado. A hospedagem do aplicativo também pode envolver fornecedor de infraestrutura.</p><p>Esses fornecedores podem processar dados fora do Brasil ou permitir acesso remoto a partir de outros países, conforme a região e os termos contratados. A política não afirma, sem confirmação, a localização dos dados nem o mecanismo jurídico de cada transferência internacional. Antes do lançamento, o controlador deve validar fornecedores, regiões, contratos e salvaguardas aplicáveis à transferência internacional nos termos da LGPD.</p><p>O Pixel não declara venda de dados pessoais, publicidade comportamental própria ou compartilhamento para finalidade incompatível com a operação descrita nesta página.</p></> },
  { id: "retencao-seguranca", title: "8. Retenção e segurança", children: <><p>Além da retenção local descrita acima, a conexão do Google Drive permanece enquanto estiver ativa e é removida pelo fluxo de desconexão. Como regra operacional do uso interno, os dados de conta, vínculo e acesso devem ser mantidos somente enquanto a pessoa tiver acesso ativo às plataformas da Prime Creative. Quando o acesso for encerrado ou houver pedido de eliminação validado, os dados deverão ser eliminados sem demora indevida, respeitadas hipóteses legais de conservação.</p><p>O código revisado ainda não implementa nem comprova um fluxo automático de exclusão para todos os dados do ambiente compartilhado Órbita/Supabase, nem define prazo para todos os registros técnicos. Essa automação, os critérios de validação do pedido e os prazos efetivos precisam estar definidos e comprovados antes de publicar uma promessa de exclusão imediata.</p><p>As medidas visíveis na implementação incluem autenticação de sessão, validação do vínculo ativo à equipe, separação entre navegador e operações sensíveis no servidor, cifra do refresh token do Drive e estado OAuth temporário assinado. Nenhum serviço é absolutamente seguro. A pessoa usuária deve proteger suas credenciais e dispositivo e reportar situações suspeitas pelo canal oficial de privacidade.</p></> },
  { id: "direitos", title: "9. Direitos da pessoa titular", children: <><p>Nos termos da LGPD, quando aplicável, a pessoa titular pode solicitar confirmação de tratamento, acesso, correção, anonimização, bloqueio ou eliminação de dados desnecessários ou tratados em desconformidade, portabilidade nos limites legais e regulamentares, informação sobre compartilhamentos, revogação de consentimento quando essa for a base aplicável e demais direitos previstos em lei.</p><p>Pedidos devem ser enviados ao canal de privacidade a ser confirmado antes da publicação. A resposta poderá exigir validação de identidade e considerar dados que o Pixel não controla diretamente, como arquivos já baixados, conteúdo guardado exclusivamente no navegador da pessoa ou dados sujeitos a dever de retenção legal.</p></> },
  { id: "atualizacoes", title: "10. Atualizações desta política", children: <p>Esta política será atualizada antes de qualquer mudança material no tratamento de dados, nos fornecedores, no uso de Google Drive, no fluxo de IA ou nos requisitos legais aplicáveis. Quando uma mudança exigir nova manifestação da pessoa titular, ela será solicitada antes do novo tratamento. A versão publicada indicará a data de vigência e um meio de consultar versões anteriores, se aplicável.</p> },
];

const termsSections: LegalSection[] = [
  { id: "aceite-e-responsavel", title: "1. Escopo e responsável", children: <><p>Estes Termos regulam o uso interno do Pixel, ferramenta de criação de cards e carrosséis apresentada sob o nome comercial Prime Creative. A operação é conduzida por José Rodrigues da Costa Netto, pessoa física responsável pelo produto, e não por uma pessoa jurídica chamada Prime Creative.</p><p>O canal oficial de contato é <a href="mailto:contato@primecreative.com.br">contato@primecreative.com.br</a>. Ao utilizar o Pixel, a pessoa usuária concorda com estes Termos e com a <Link href="/privacidade">Política de Privacidade</Link>. Estes documentos não afastam direitos assegurados por lei, inclusive os do Código de Defesa do Consumidor quando houver relação de consumo.</p></> },
  { id: "acesso", title: "2. Acesso e conta", children: <><p>O acesso depende de sessão válida na autenticação compartilhada do ambiente Órbita/Supabase e de vínculo ativo com o espaço de trabalho autorizado. O Pixel não cria conta independente para esse fim. A disponibilidade do acesso pode ser afetada por sessão expirada, vínculo inativo, configuração ausente ou indisponibilidade de serviço de terceiro.</p><p>A pessoa usuária deve manter as credenciais sob sigilo e utilizar o Pixel dentro das permissões concedidas. O acesso pode ser suspenso ou encerrado por perda do vínculo autorizado, exigência de segurança, uso que viole estes Termos ou obrigação legal, sem prejuízo das garantias aplicáveis e de comunicações cabíveis no contexto da relação.</p></> },
  { id: "uso-e-conteudo", title: "3. Uso permitido e conteúdo", children: <><p>O Pixel permite compor peças visuais a partir de templates, textos, imagens e dados inseridos pela pessoa usuária, e exportar o resultado em PNG, JPG ou ZIP. Use o produto de forma lícita e respeite direitos autorais, direitos de imagem, marcas, proteção de dados, normas publicitárias e demais direitos de terceiros.</p><p>A pessoa usuária responde por ter autorização para inserir e usar o conteúdo que envia, bem como por revisar as peças antes de publicá-las. O Pixel não substitui revisão editorial, jurídica, publicitária, de acessibilidade ou de conformidade com regras de plataformas externas. Estes Termos não transferem ao responsável pelo Pixel a titularidade do conteúdo da pessoa usuária; esta concede apenas a autorização técnica limitada necessária para processá-lo localmente, renderizar e gerar a exportação solicitada e, se escolher Drive, enviar os arquivos por ela selecionados.</p></> },
  { id: "local-e-exportacoes", title: "4. Criações locais e exportações", children: <><p>As criações são mantidas no navegador por meio de armazenamento local. A pessoa pode definir uma retenção de 15, 30 ou 90 dias, ou de 1 a 365 dias. A exclusão local pode ocorrer ao recarregar o aplicativo após a expiração e poderá também ocorrer se os dados do navegador forem limpos, se o dispositivo ou perfil for trocado ou se a criação for apagada manualmente.</p><p>Os arquivos baixados ou enviados ao Drive deixam o controle técnico direto do Pixel conforme o destino escolhido. A pessoa usuária é responsável por conferir nome, conteúdo, formato e local de destino antes de compartilhar ou publicar uma exportação.</p></> },
  { id: "ia", title: "5. Sugestão de texto por IA, quando disponível", children: <><p>A função de interpretação de briefing é opcional e somente opera quando habilitada no ambiente e acionada pela pessoa usuária. Ela envia briefing textual, contexto de público ou tom de voz e template ao serviço de IA configurado para devolver uma sugestão de conteúdo. Não envie informação pessoal sensível, confidencial ou de terceiros sem avaliação e autorização adequadas.</p><p>A sugestão não é garantia de exatidão, originalidade, adequação jurídica, ausência de vieses ou disponibilidade. A pessoa usuária deve revisá-la antes de gerar, exportar, divulgar ou tomar decisão com base nela.</p></> },
  { id: "drive", title: "6. Google Drive opcional", children: <><p>Ao escolher conectar uma conta Google, a pessoa usuária inicia um fluxo OAuth com o escopo <code>drive.file</code>. O Pixel cria uma pasta chamada <strong>Pixel</strong> e só envia exportações quando a pessoa usar os comandos de envio. A integração não implementa leitura de biblioteca, importação, sincronização bidirecional ou listagem geral de arquivos da conta.</p><p>A desconexão tenta revogar a autorização no Google e remove a conexão cifrada guardada pelo Pixel. Se a revogação no Google não for concluída, a pessoa poderá remover o acesso diretamente nas configurações de apps de terceiros da Conta Google. Aplicam-se também a <Link href="/privacidade#drive">seção de privacidade do Drive</Link> e as políticas aplicáveis do Google.</p></> },
  { id: "disponibilidade", title: "7. Alterações, disponibilidade e suporte", children: <><p>O Pixel pode receber correções, ajustes de segurança, mudanças de interface e evolução de funcionalidades. O responsável buscará comunicar mudanças relevantes por meio razoável antes de sua vigência, especialmente quando elas exigirem nova manifestação da pessoa usuária ou alterarem materialmente o tratamento de dados.</p><p>Não é prometida disponibilidade ininterrupta, preservação de criações exclusivamente locais, resultado estético específico ou compatibilidade com todo navegador e dispositivo. Isso não exclui responsabilidades que a legislação não permita excluir ou limitar. O canal de suporte e de privacidade é <a href="mailto:contato@primecreative.com.br">contato@primecreative.com.br</a>.</p></> },
  { id: "responsabilidade", title: "8. Responsabilidades e limites legais", children: <p>Na extensão permitida pela lei, o Pixel é uma ferramenta de criação e exportação. O responsável não garante que toda peça gerada seja adequada a uma finalidade específica, às políticas de terceiros ou a exigências jurídicas e regulatórias particulares. Nada nestes Termos limita direitos irrenunciáveis, responsabilidade por atos que a lei não permita limitar ou a proteção da pessoa consumidora quando aplicável.</p> },
  { id: "lei-aplicavel", title: "9. Lei aplicável e solução de conflitos", children: <p>Aplica-se a legislação brasileira às relações abrangidas por estes Termos, sem prejuízo de normas de proteção obrigatória aplicáveis. Eventual controvérsia será submetida ao foro competente definido pela legislação, inclusive as regras de proteção ao consumidor quando cabíveis. Estes Termos não impõem foro exclusivo que restrinja direitos legalmente assegurados.</p> },
  { id: "atualizacoes", title: "10. Contato e atualizações", children: <><p>Dúvidas sobre uso, estes Termos ou privacidade devem ser dirigidas a <a href="mailto:contato@primecreative.com.br">contato@primecreative.com.br</a>. Até a confirmação operacional das pendências indicadas na Política de Privacidade, este é um rascunho de revisão e não uma versão final de lançamento.</p><p>A versão vigente ficará disponível nesta página com data de atualização. Mudanças materiais serão comunicadas de forma compatível com a relação e com a lei aplicável.</p></> },
];

function LegalHeader() {
  return <header className={styles.header}><Link href="/" className={styles.brand} aria-label="Voltar ao Pixel"><img src="/brand/pixel/signature/lockup-wide-ink.svg" alt="Pixel, um produto Prime Creative" /></Link><Link href="/" className={styles.loginLink}>Entrar no Pixel</Link></header>;
}

function LegalFooter({ current }: { current: "privacy" | "terms" }) {
  return <footer className={styles.footer}><span>Pixel · Prime Creative</span><nav aria-label="Documentos legais">{current !== "privacy" && <Link href="/privacidade">Política de Privacidade</Link>}{current !== "terms" && <Link href="/termos">Termos de Uso</Link>}<Link href="/">Entrar</Link></nav></footer>;
}

export function LegalPage({ kind }: { kind: "privacy" | "terms" }) {
  const isPrivacy = kind === "privacy";
  const sections = isPrivacy ? privacySections : termsSections;
  const title = isPrivacy ? "Política de Privacidade" : "Termos de Uso";
  const subtitle = isPrivacy ? "Como o Pixel trata dados de acesso, criações locais e recursos opcionais." : "As condições de uso do Pixel e de suas exportações.";
  return <main className={styles.shell}><LegalHeader /><article className={styles.document}><div className={styles.hero}><p className="eyebrow">Pixel · Prime Creative</p><h1>{title}</h1><p>{subtitle}</p><small>Revisado em: 10 de outubro de 2026 · versão pendente de confirmação para publicação</small></div>{publishingNotice}<div className={styles.content}>{sections.map((section) => <section id={section.id} key={section.id}><h2>{section.title}</h2>{section.children}</section>)}</div></article><LegalFooter current={kind} /></main>;
}
